import type { Metadata } from "next";
import { LegalLayout } from "@/components/legal-layout";
import { Callout } from "@/components/ui/callout";
import { TOCItem } from "@/components/ui/table-of-contents";
import { Card, CardContent } from "@/components/ui/card";
import { Brain, TrendingUp, Target, BarChart3, Clock, Award } from "lucide-react";

export const metadata: Metadata = {
  title: "Ranking Methodology | Kelucalls",
  description:
    "Learn how Kelucalls ranks Telegram crypto channels - Understand our Smart Score, ROI calculations, and ranking metrics.",
  alternates: {
    canonical: "/ranking-methodology",
  },
};

const toc: TOCItem[] = [
  { id: "overview", title: "Overview" },
  { id: "smart-score", title: "Smart Score" },
  { id: "average-roi", title: "Average ROI" },
  { id: "win-rate", title: "Win Rate" },
  { id: "peak-roi", title: "Peak ROI" },
  { id: "call-volume", title: "Number of Calls" },
  { id: "consistency", title: "Consistency" },
  { id: "historical", title: "Historical Performance" },
  { id: "milestones", title: "Milestones" },
  { id: "algorithm", title: "Our Algorithm" },
  { id: "transparency", title: "Transparency" },
];

export default function RankingMethodologyPage() {
  return (
    <LegalLayout
      title="Ranking Methodology"
      description="Understanding how we calculate channel rankings and what our metrics mean."
      lastUpdated="July 11, 2026"
      toc={toc}
    >
      <h2 id="overview">Overview</h2>
      <p>
        Our ranking system is designed to help users identify high-performing
        crypto signal channels through transparent, data-driven metrics. All
        rankings are generated algorithmically based on historical tracked call
        performance—no manual intervention influences the leaderboard.
      </p>

      <Callout variant="info" title="Data-Driven">
        Rankings are based purely on performance data. We do not accept payment to
        influence rankings, and sponsored content is always clearly labeled.
      </Callout>

      <h2 id="smart-score">Smart Score</h2>
      <div className="not-prose my-8">
        <Card className="border-cyan-400/30 bg-gradient-to-r from-cyan-400/10 to-transparent">
          <CardContent className="p-6">
            <div className="flex items-center gap-4">
              <div className="flex size-14 items-center justify-center rounded-xl bg-cyan-400/20">
                <Brain className="size-7 text-cyan-400" />
              </div>
              <div>
                <h3 className="text-lg font-semibold text-white">Smart Score</h3>
                <p className="text-sm text-slate-400">
                  Our proprietary composite score (0-100) that combines multiple metrics
                  to provide a comprehensive view of channel performance.
                </p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
      <p>
        The Smart Score is our proprietary composite metric that combines multiple
        performance indicators into a single score. It weighs factors including
        ROI, win rate, consistency, and call volume to provide a balanced
        assessment of channel quality.
      </p>
      <p>
        A higher Smart Score indicates a channel that performs well across
        multiple dimensions, not just in one area.
      </p>

      <h2 id="average-roi">Average ROI</h2>
      <div className="not-prose my-8">
        <Card className="border-emerald-400/30 bg-gradient-to-r from-emerald-400/10 to-transparent">
          <CardContent className="p-6">
            <div className="flex items-center gap-4">
              <div className="flex size-14 items-center justify-center rounded-xl bg-emerald-400/20">
                <TrendingUp className="size-7 text-emerald-400" />
              </div>
              <div>
                <h3 className="text-lg font-semibold text-white">Average ROI</h3>
                <p className="text-sm text-slate-400">
                  The mean return on investment across all tracked calls, expressed as a percentage.
                </p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
      <p>
        Average ROI measures the mean return generated by all calls from a channel.
        It&apos;s calculated by taking the percentage gain or loss for each call that
        hit its target and averaging them together.
      </p>
      <p>
        For example, if a channel made 10 calls and 7 hit targets with returns of
        +5%, +10%, +20%, +8%, +15%, +12%, and +25%, the average ROI would be
        approximately 13.6%.
      </p>

      <h2 id="win-rate">Win Rate</h2>
      <div className="not-prose my-8">
        <Card className="border-blue-400/30 bg-gradient-to-r from-blue-400/10 to-transparent">
          <CardContent className="p-6">
            <div className="flex items-center gap-4">
              <div className="flex size-14 items-center justify-center rounded-xl bg-blue-400/20">
                <Target className="size-7 text-blue-400" />
              </div>
              <div>
                <h3 className="text-lg font-semibold text-white">Win Rate</h3>
                <p className="text-sm text-slate-400">
                  The percentage of calls that successfully hit their stated price targets.
                </p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
      <p>
        Win Rate represents the percentage of calls that successfully hit their
        stated price targets within the specified timeframe. It&apos;s a key indicator
        of a channel&apos;s reliability.
      </p>
      <p>
        A channel with a high win rate (70%+) demonstrates consistent ability to
        predict price movements. However, win rate alone doesn&apos;t tell the full
        story—a channel with many small wins might have lower average ROI than one
        with fewer but larger wins.
      </p>

      <h2 id="peak-roi">Peak ROI</h2>
      <div className="not-prose my-8">
        <Card className="border-purple-400/30 bg-gradient-to-r from-purple-400/10 to-transparent">
          <CardContent className="p-6">
            <div className="flex items-center gap-4">
              <div className="flex size-14 items-center justify-center rounded-xl bg-purple-400/20">
                <Award className="size-7 text-purple-400" />
              </div>
              <div>
                <h3 className="text-lg font-semibold text-white">Peak ROI</h3>
                <p className="text-sm text-slate-400">
                  The highest return achieved by a single call from this channel.
                </p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
      <p>
        Peak ROI shows the highest single-call return achieved by a channel. This
        metric highlights a channel&apos;s potential for significant gains, even if
        such calls are rare.
      </p>

      <h2 id="call-volume">Number of Calls</h2>
      <div className="not-prose my-8">
        <Card className="border-amber-400/30 bg-gradient-to-r from-amber-400/10 to-transparent">
          <CardContent className="p-6">
            <div className="flex items-center gap-4">
              <div className="flex size-14 items-center justify-center rounded-xl bg-amber-400/20">
                <BarChart3 className="size-7 text-amber-400" />
              </div>
              <div>
                <h3 className="text-lg font-semibold text-white">Number of Calls</h3>
                <p className="text-sm text-slate-400">
                  The total count of tracked crypto signals from this channel.
                </p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
      <p>
        The total number of tracked calls provides context for the other metrics.
        A channel with only 5 calls and 80% win rate has less statistical
        significance than one with 500 calls and the same win rate.
      </p>
      <p>
        We use call volume to ensure our rankings reflect consistent performance
        rather than short-term luck.
      </p>

      <h2 id="consistency">Consistency</h2>
      <div className="not-prose my-8">
        <Card className="border-cyan-400/30 bg-gradient-to-r from-cyan-400/10 to-transparent">
          <CardContent className="p-6">
            <div className="flex items-center gap-4">
              <div className="flex size-14 items-center justify-center rounded-xl bg-cyan-400/20">
                <Clock className="size-7 text-cyan-400" />
              </div>
              <div>
                <h3 className="text-lg font-semibold text-white">Consistency</h3>
                <p className="text-sm text-slate-400">
                  A measure of how reliably a channel performs over time.
                </p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
      <p>
        Consistency measures how reliably a channel performs over time. Channels
        that maintain steady performance month after month score higher than those
        with highly variable results.
      </p>
      <p>
        This metric helps identify channels that users can rely on long-term,
        rather than those that have occasional lucky streaks.
      </p>

      <h2 id="historical">Historical Performance</h2>
      <p>
        We track and display historical performance data to help users evaluate
        how channels have performed over different time periods:
      </p>
      <ul>
        <li>
          <strong>7 Days:</strong> Recent short-term performance
        </li>
        <li>
          <strong>30 Days:</strong> Medium-term trends
        </li>
        <li>
          <strong>90 Days:</strong> Quarterly performance
        </li>
        <li>
          <strong>All Time:</strong> Historical track record
        </li>
      </ul>
      <p>
        This allows users to see whether a channel&apos;s performance is consistent
        or has varied significantly over time.
      </p>

      <h2 id="milestones">Milestones</h2>
      <p>
        We celebrate significant achievements with milestone badges. These are
        automatically awarded when channels hit certain performance thresholds:
      </p>
      <div className="not-prose my-8 grid gap-4 sm:grid-cols-3">
        <div className="rounded-2xl border border-white/10 bg-white/5 p-5 text-center">
          <div className="mb-2 text-2xl font-bold text-emerald-400">2x</div>
          <div className="text-sm text-slate-400">Called a 2x winner</div>
        </div>
        <div className="rounded-2xl border border-white/10 bg-white/5 p-5 text-center">
          <div className="mb-2 text-2xl font-bold text-purple-400">10x</div>
          <div className="text-sm text-slate-400">Called a 10x winner</div>
        </div>
        <div className="rounded-2xl border border-white/10 bg-white/5 p-5 text-center">
          <div className="mb-2 text-2xl font-bold text-amber-400">100x</div>
          <div className="text-sm text-slate-400">Called a 100x winner</div>
        </div>
      </div>

      <h2 id="algorithm">Our Algorithm</h2>
      <Callout variant="warning" title="Proprietary">
        We don&apos;t expose exact formulas to prevent gaming, but the algorithm is
        designed to reward genuine performance.
      </Callout>
      <p>
        Our ranking algorithm combines all the above metrics into a comprehensive
        score. The algorithm is designed to:
      </p>
      <ul>
        <li>Reward consistent, long-term performance</li>
        <li>Balance ROI against win rate and call volume</li>
        <li>Consider recent performance more heavily than older data</li>
        <li>Prevent short-term manipulation</li>
        <li>Provide meaningful differentiation between channels</li>
      </ul>

      <h2 id="transparency">Transparency Commitment</h2>
      <p>
        Kelucalls is committed to transparency in our ranking methodology:
      </p>
      <ul>
        <li>All rankings are algorithmically generated</li>
        <li>Sponsored content is clearly labeled and separate</li>
        <li>We never accept payment to influence rankings</li>
        <li>Users can see the underlying data behind any ranking</li>
        <li>We welcome feedback and questions about our methodology</li>
      </ul>
      <p>
        If you have questions about our methodology, please contact us at{" "}
        <a href="mailto:support@kelucalls.com" className="text-cyan-400 hover:underline">
          support@kelucalls.com
        </a>
        .
      </p>
    </LegalLayout>
  );
}